set -g base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Z last-pane \; resize-pane -Z
bind _ resize-pane -y 100%
bind + resize-pane -y 50%

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -wg mode-keys vi
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g status-position top

run '~/.tmux/plugins/tpm/tpm'

set -g status-right "#[bg=#(pomodoro tmux-colors)] #(pomodoro status --format '%%!R ⏱ %%c/%%g 🍅 %%d') || %H:%M"
